### ISSUE TITLE
auction creation route

### ISSUE THREAD

**Issue by andriotisnikos1** [Tonantzintla/MinionAH-Bot#2]
we need this route for #1.

@DarthGigi has to push a public POST route for minion auction creation

ideal url: `/api/discord/auctions`

here is the interface for the request:

```typescript
interface AuctionCreationBody {
    discordID: string;
    auction: {
        type: string;
        tier: number;
        amount: number;
        price: number;
        mithrilInfused: boolean;
    }
}
```

**Comment by DarthGigi** [comment]
Send a `POST` request to `api/bot/auction`
