### ISSUE TITLE
auction deletion route

### ISSUE THREAD

**Issue by andriotisnikos1** [Tonantzintla/MinionAH-Bot#3]
we need this route for #4 .

@DarthGigi has to push a public DELETE route for minion auction deletion

ideal url: `/api/discord/auctions`

here is the interface for the request:

```typescript
interface AuctionDeletionBody {
    discordID: string;
    auctionID: string;
}
```

**Comment by DarthGigi** [comment]
Send a `DELETE` request to `api/bot/auction`
